### ISSUE TITLE
Does not work in Firefox

### ISSUE THREAD

**Issue by EnxGitHub** [ibrahimcesar/react-quicklink#1]
I get this error:

TypeError: connection is undefined
QuickLink/<
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-quicklink/dist/QuickLink.js:23

  20 | var allowedOptions = allowedOrigins || [window.location.hostname];
  21 | var allowed = allowedOptions === current.hostname;
  22 | var connection = navigator.connection || navigator.mozConnection || navigator.webkitConnection;
> 23 | var type = connection.effectiveType;
     | ^  24 | var thresholdType = effectiveTypes.indexOf(connType);
  25 | var types = effectiveTypes.filter(function (t, i) {
  26 |   return i >= thresholdType;

invokePassiveEffectCreate
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:23487

  23484 | 
  23485 | function invokePassiveEffectCreate(effect) {
  23486 |   var create = effect.create;
> 23487 |   effect.destroy = create();
  23488 | }
  23489 | 
  23490 | function flushPassiveEffectsImpl() {

callCallback
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:3945

  3942 | function callCallback() {
  3943 |   didCall = true;
  3944 |   restoreAfterDispatch();
> 3945 |   func.apply(context, funcArgs);
       | ^  3946 |   didError = false;
  3947 | } // Create a global error event handler. We use this to capture the value
  3948 | // that was thrown. It's possible that this error handler will fire more

invokeGuardedCallbackDev
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:3994

  3991 | // errors, it will trigger our global error handler.
  3992 | 
  3993 | evt.initEvent(evtType, false, false);
> 3994 | fakeNode.dispatchEvent(evt);
       | ^  3995 | 
  3996 | if (windowEventDescriptor) {
  3997 |   Object.defineProperty(window, 'event', windowEventDescriptor);

invokeGuardedCallback
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:4056

  4053 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  4054 |   hasError = false;
  4055 |   caughtError = null;
> 4056 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  4057 | }
  4058 | /**
  4059 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores

flushPassiveEffectsImpl
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:23574

  23571 | setCurrentFiber(_fiber);
  23572 | 
  23573 | {
> 23574 |   invokeGuardedCallback(null, invokePassiveEffectCreate, null, _effect2);
        | ^  23575 | }
  23576 | 
  23577 | if (hasCaughtError()) {

unstable_runWithPriority
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/scheduler/cjs/scheduler.development.js:646

  643 | currentPriorityLevel = priorityLevel;
  644 | 
  645 | try {
> 646 |   return eventHandler();
      | ^  647 | } finally {
  648 |   currentPriorityLevel = previousPriorityLevel;
  649 | }

runWithPriority$1
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:11276

  11273 | 
  11274 | function runWithPriority$1(reactPriorityLevel, fn) {
  11275 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 11276 |   return Scheduler_runWithPriority(priorityLevel, fn);
  11277 | }
  11278 | function scheduleCallback(reactPriorityLevel, callback, options) {
  11279 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);

flushPassiveEffects
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:23447

  23444 |   pendingPassiveEffectsRenderPriority = NoPriority$1;
  23445 | 
  23446 |   {
> 23447 |     return runWithPriority$1(priorityLevel, flushPassiveEffectsImpl);
        | ^  23448 |   }
  23449 | }
  23450 | 

performSyncWorkOnRoot
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:22269

  22266 |   }
  22267 | }
  22268 | 
> 22269 | flushPassiveEffects();
        | ^  22270 | var lanes;
  22271 | var exitStatus;
  22272 | 

flushSyncCallbackQueueImpl/<
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:11327

  11324 |     var callback = _queue[i];
  11325 | 
  11326 |     do {
> 11327 |       callback = callback(_isSync2);
        | ^  11328 |     } while (callback !== null);
  11329 |   }
  11330 | });

unstable_runWithPriority
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/scheduler/cjs/scheduler.development.js:646

  643 | currentPriorityLevel = priorityLevel;
  644 | 
  645 | try {
> 646 |   return eventHandler();
      | ^  647 | } finally {
  648 |   currentPriorityLevel = previousPriorityLevel;
  649 | }

runWithPriority$1
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:11276

  11273 | 
  11274 | function runWithPriority$1(reactPriorityLevel, fn) {
  11275 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 11276 |   return Scheduler_runWithPriority(priorityLevel, fn);
  11277 | }
  11278 | function scheduleCallback(reactPriorityLevel, callback, options) {
  11279 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);

flushSyncCallbackQueueImpl
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:11322

  11319 | try {
  11320 |   var _isSync2 = true;
  11321 |   var _queue = syncQueue;
> 11322 |   runWithPriority$1(ImmediatePriority$1, function () {
        | ^  11323 |     for (; i < _queue.length; i++) {
  11324 |       var callback = _queue[i];
  11325 | 

flushSyncCallbackQueue
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:11309

  11306 |     Scheduler_cancelCallback(node);
  11307 |   }
  11308 | 
> 11309 |   flushSyncCallbackQueueImpl();
  11310 | }
  11311 | 
  11312 | function flushSyncCallbackQueueImpl() {

unbatchedUpdates
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:22438

  22435 |     if (executionContext === NoContext) {
  22436 |       // Flush the immediate callbacks that were scheduled during this batch
  22437 |       resetRenderTimer();
> 22438 |       flushSyncCallbackQueue();
  22439 |     }
  22440 |   }
  22441 | }

legacyRenderSubtreeIntoContainer
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:26020

  26017 |   } // Initial mount should not be batched.
  26018 | 
  26019 | 
> 26020 |   unbatchedUpdates(function () {
        | ^  26021 |     updateContainer(children, fiberRoot, parentComponent, callback);
  26022 |   });
  26023 | } else {

render
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/node_modules/react-dom/cjs/react-dom.development.js:26103

  26100 |     }
  26101 |   }
  26102 | 
> 26103 |   return legacyRenderSubtreeIntoContainer(null, element, container, false, callback);
  26104 | }
  26105 | function unstable_renderSubtreeIntoContainer(parentComponent, element, containerNode, callback) {
  26106 |   if (!isValidContainer(containerNode)) {

./src/index.js/<
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/src/index.js:7

   4 | import App from "./App.jsx";
   5 | import reportWebVitals from "./reportWebVitals";
   6 | 
>  7 | ReactDOM.render(
   8 |     <React.StrictMode>
   9 |         <App grafik={true} tablo={true} />
  10 |     </React.StrictMode>,

./src/index.js
http://localhost:3000/static/js/main.chunk.js:1721:30
__webpack_require__
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

fn
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

1
http://localhost:3000/static/js/main.chunk.js:1844:18
__webpack_require__
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

checkDeferredModules
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/webpack/bootstrap:45

  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 

webpackJsonpCallback
C:/Users/casper/Documents/Coding/Local/kovidbot/kovidbot.web.app/webpack/bootstrap:32

  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;

**Comment by ibrahimcesar** [comment]
I'll investigate and create a patch. Thanks for reporting

**Comment by ibrahimcesar** [comment]
- [ ] test
